server:
  port: ${server_port:8084}

spring:
  application: 
    name: iceandfire_service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
    command:
        AnyService:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 15000

