server:
  port: ${server_port:8084}

spring:
  application: 
    name: iceandfire-service
  boot:
    admin:
      url: http://localhost:8088
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
    command:
        AnyService:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 15000

