server:
  port: ${server_port:8084}

spring:
  application: 
    name: iceandfire_service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

iceandfire:
    houses:
        dbUrl: http://localhost:8082/houses/search/
    swornMembers:
        dbUrl: http://localhost:8082/swornMembers/search/