server:
  port: 8083
spring:
  application:
    name: iceandfire-frontend
  boot:
    admin:
      url: ${ADMIN_URL:http://localhost:8088}
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
   