server:
  port: 8080
spring:
  application: 
    name: iceandfire-import
  boot:
    admin:
      url: ${ADMIN_URL:http://localhost:8088}
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

iceandfire:
    houses:
        baseUrl: https://www.anapioficeandfire.com/api/houses/
        dbUrl: http://iceandfiredb/houses
    characters:
        baseUrl: https://www.anapioficeandfire.com/api/characters/
        dbUrl: http://iceandfiredb/swornMembers
    regions:
        The North: 7
        Iron Islands: 4
        The Riverlands: 6
        The Vale: 4
        The Westerlands: 6
        The Crownlands: 5
        The Reach: 8
        The Stormlands: 4
        Dorne: 3
        