server:
  port: ${server_port:8761}
management:
  security:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0