server:
  port: 8088
spring:
  application:
    name: springbootadmin
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    