server:
  port: 8000

spring:
  application: 
    name: iceandfire_proxy
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
  routes:
    frontend:
      path: /**
      service-id: iceandfire_frontend
    import:
      path: /iceandfire/**
      service-id: iceandfire_import
      strip-prefix: false
    service:
      path: /service/**
      service-id: iceandfire_service
      strip-prefix: false
    