server:
  port: 8000

spring:
  application: 
    name: iceandfire-proxy
  boot:
    admin:
      url: http://localhost:8088
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

zuul:
  routes:
    frontend:
      path: /**
      service-id: iceandfire-frontend
    import:
      path: /iceandfire/**
      service-id: iceandfire-import
      strip-prefix: false
    service:
      path: /service/**
      service-id: iceandfire-service
      strip-prefix: false
    