server:
  port: 8000

spring:
  application: 
    name: iceandfire_proxy
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
  routes:
    frontend:
      path: /**
      url: http://localhost:8081/
    import:
      path: /iceandfire/**
      url: http://localhost:8080/iceandfire
    service:
      path: /service/**
      url: http://localhost:8084/service
    