server:
  port: 8000

spring:
  application: 
    name: iceandfire_proxy
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  routes:
    frontend:
      path: /**
      service-id: iceandfire_frontend
    import:
      path: /iceandfire/**
      service-id: iceandfire_import
      strip-prefix: false
    service:
      path: /service/**
      service-id: iceandfire_service
      strip-prefix: false
    